# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Marco/Projeto_final_ULA/Projeto_final_ULA.cache/wt [current_project]
set_property parent.project_path C:/Users/Marco/Projeto_final_ULA/Projeto_final_ULA.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib C:/Users/Marco/Projeto_final_ULA/Projeto_final_ULA.srcs/sources_1/new/ULA.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Marco/Google Drive/Engenharia/SD1/PED/rel 7/lab_07/contador_1/Basys3_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Marco/Google Drive/Engenharia/SD1/PED/rel 7/lab_07/contador_1/Basys3_Master.xdc}}]


synth_design -top ULA -part xc7a35tcpg236-1


write_checkpoint -force -noxdef ULA.dcp

catch { report_utilization -file ULA_utilization_synth.rpt -pb ULA_utilization_synth.pb }
