# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Marco/prerel6/prerel6.cache/wt [current_project]
set_property parent.project_path C:/Users/Marco/prerel6/prerel6.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib C:/Users/Marco/prerel6/prerel6.srcs/sources_1/new/prerel6.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Marco/Desktop/PED/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/Users/Marco/Desktop/PED/Basys3_Master.xdc]


synth_design -top HEX_to_SSEG -part xc7a35tcpg236-1


write_checkpoint -force -noxdef HEX_to_SSEG.dcp

catch { report_utilization -file HEX_to_SSEG_utilization_synth.rpt -pb HEX_to_SSEG_utilization_synth.pb }
